SELECT NUM, COUNT(*)
FROM (
SELECT A, COUNT(DISTINCT B, D) AS NUM
FROM R4
GROUP BY A
) X
GROUP BY NUM;

SELECT IF (COUNT(*) = 0, 'MAYBE MVD', 'NO MVD') AS MVD
FROM (SELECT A
      FROM R2
      GROUP BY A
      HAVING (COUNT(DISTINCT B) * COUNT(DISTINCT C)
                   <> COUNT(*))
) X;
